// Seed recipes — match the Recipe interface from the spec
window.SEED_RECIPES = [
  {
    id: "r-panzanella",
    title: "Late-Summer Panzanella",
    types: ["italian", "starter"],
    description: "A loose, generous bread salad — every fridge raid welcome. Mostly an excuse for stale sourdough and a bottle of good vinegar.",
    ingredients: [
      { id: "i1", amount: "400g", name: "day-old sourdough, torn" },
      { id: "i2", amount: "5", name: "ripe heirloom tomatoes" },
      { id: "i3", amount: "200g", name: "cherry tomatoes, halved" },
      { id: "i4", amount: "1", name: "cucumber, peeled in strips" },
      { id: "i5", amount: "1 small", name: "red onion, sliced thin" },
      { id: "i6", amount: "1", name: "yellow pepper, charred" },
      { id: "i7", amount: "100g", name: "Castelvetrano olives, torn" },
      { id: "i8", amount: "8", name: "anchovy fillets" },
      { id: "i9", amount: "2 tbsp", name: "capers in brine" },
      { id: "i10", amount: "1 bunch", name: "basil, leaves only" },
      { id: "i11", amount: "1 small bunch", name: "flat-leaf parsley" },
      { id: "i12", amount: "1 ball", name: "burrata (optional but right)" },
      { id: "i13", amount: "6 tbsp", name: "extra virgin olive oil" },
      { id: "i14", amount: "3 tbsp", name: "red wine vinegar" },
      { id: "i15", amount: "1 clove", name: "garlic, grated" },
      { id: "i16", amount: "1 tsp", name: "Dijon mustard" },
      { id: "i17", amount: "to taste", name: "flaky salt + black pepper" },
    ],
    steps: [
      { id: "s1", order: 1, description: "Toast the torn bread with 2 tbsp of the olive oil and a good pinch of salt at 200°C / 400°F for 8–10 minutes until golden but still chewy in the middle. Cool on the tray." },
      { id: "s2", order: 2, description: "Whisk the remaining olive oil, vinegar, garlic, and mustard in the bottom of a big bowl. Add the tomatoes and a generous pinch of salt; let them sit for 10 minutes to draw out their juice." },
      { id: "s3", order: 3, description: "Pile in everything else — bread, cucumber, onion, pepper, olives, anchovies, capers, herbs. Toss with your hands until soaked. Tear the burrata over the top, finish with flaky salt and pepper, and serve immediately." },
    ],
    notes: "The bread should drink up the dressing — that's the whole point. If you have an extra 20 minutes, salt the cucumber slices in a colander first to draw out water; it makes a real difference. Day-two leftovers are mush, but excellent mush.",
    createdAt: "2026-04-29T13:30:00.000Z",
  },
  {
    id: "r-tomato-bread",
    title: "Slow-Roasted Tomato Bread",
    types: ["starter", "italian"],
    description: "Sweet, jammy tomatoes piled on toasted sourdough with sea salt and good olive oil. A late-summer ritual.",
    ingredients: [
      { id: "i1", amount: "8", name: "ripe vine tomatoes" },
      { id: "i2", amount: "4 tbsp", name: "extra virgin olive oil" },
      { id: "i3", amount: "1 tsp", name: "flaky sea salt" },
      { id: "i4", amount: "2 sprigs", name: "thyme" },
      { id: "i5", amount: "4 thick slices", name: "sourdough" },
      { id: "i6", amount: "1 clove", name: "garlic, halved" },
    ],
    steps: [
      { id: "s1", order: 1, description: "Heat oven to 140°C / 285°F. Halve the tomatoes and lay them cut-side up on a parchment-lined tray." },
      { id: "s2", order: 2, description: "Drizzle generously with olive oil, scatter thyme and salt. Roast for 1 hour 45 minutes until shrunken and sweet." },
      { id: "s3", order: 3, description: "Toast the sourdough until deeply golden. Rub each slice with the cut side of the garlic clove." },
      { id: "s4", order: 4, description: "Pile tomatoes onto the toast. Spoon over the rich oil from the tray. Finish with extra salt." },
    ],
    notes: "The roasting oil is liquid gold — save any leftover in a small jar for pasta the next day. Works equally well with cherry tomatoes; reduce roasting time to 50 minutes.",
    createdAt: "2026-04-12T09:14:00.000Z",
  },
  {
    id: "r-miso-butter",
    title: "Miso Butter Mushrooms",
    types: ["asian", "main"],
    description: "Earthy mushrooms glazed in a salty-sweet miso butter. Twenty minutes start to finish.",
    ingredients: [
      { id: "i1", amount: "500g", name: "mixed mushrooms (oyster, shiitake, chestnut)" },
      { id: "i2", amount: "3 tbsp", name: "unsalted butter" },
      { id: "i3", amount: "2 tbsp", name: "white miso paste" },
      { id: "i4", amount: "1 tbsp", name: "soy sauce" },
      { id: "i5", amount: "1 tsp", name: "rice vinegar" },
      { id: "i6", amount: "2", name: "spring onions, sliced" },
      { id: "i7", amount: "1 tsp", name: "toasted sesame seeds" },
    ],
    steps: [
      { id: "s1", order: 1, description: "Tear larger mushrooms into bite-sized pieces. Leave smaller ones whole — variety in shape is the point." },
      { id: "s2", order: 2, description: "Whisk the miso, soy, and rice vinegar in a small bowl until smooth. Set aside." },
      { id: "s3", order: 3, description: "Heat a wide pan over high heat. Add butter; once it foams, add mushrooms in a single layer. Don't stir for 3 minutes — let them brown." },
      { id: "s4", order: 4, description: "Toss and cook another 4 minutes. Pour in the miso mixture and stir until everything is glossy and coated." },
      { id: "s5", order: 5, description: "Off the heat, scatter spring onions and sesame seeds. Serve over rice or thick toast." },
    ],
    notes: "Don't crowd the pan — work in two batches if needed. The browning is what makes this dish.",
    createdAt: "2026-03-28T18:42:00.000Z",
  },
  {
    id: "r-lemon-cake",
    title: "Almond Olive Oil Cake",
    types: ["dessert", "italian"],
    description: "Tender, fragrant, and forgiving. Keeps for days and tastes better on the second.",
    ingredients: [
      { id: "i1", amount: "200g", name: "ground almonds" },
      { id: "i2", amount: "100g", name: "fine semolina" },
      { id: "i3", amount: "180g", name: "caster sugar" },
      { id: "i4", amount: "3 large", name: "eggs" },
      { id: "i5", amount: "180ml", name: "good olive oil" },
      { id: "i6", amount: "2", name: "lemons, zest and juice" },
      { id: "i7", amount: "1 tsp", name: "baking powder" },
      { id: "i8", amount: "pinch", name: "fine sea salt" },
    ],
    steps: [
      { id: "s1", order: 1, description: "Heat oven to 170°C / 340°F. Line a 22cm round tin with parchment." },
      { id: "s2", order: 2, description: "Whisk eggs and sugar in a large bowl until pale and slightly thickened, about 2 minutes." },
      { id: "s3", order: 3, description: "Stream in the olive oil while whisking, then add lemon zest and juice." },
      { id: "s4", order: 4, description: "Fold in the dry ingredients gently — don't overmix. The batter should be loose and fragrant." },
      { id: "s5", order: 5, description: "Pour into the tin, smooth the top, and bake 40–45 minutes until a skewer comes out with a few moist crumbs." },
      { id: "s6", order: 6, description: "Cool in the tin for 15 minutes, then turn out. Dust with icing sugar to serve." },
    ],
    notes: "Use a fruity, peppery olive oil — it's a flavour, not a fat substitute. A dollop of crème fraîche and a few raspberries on the side is all this needs.",
    createdAt: "2026-02-15T11:20:00.000Z",
  },
  {
    id: "r-leek-soup",
    title: "Leek & Potato Soup, Properly",
    types: ["main", "starter"],
    description: "The classic. Buttery, silky, restrained — the kind of bowl you make on a grey Sunday.",
    ingredients: [
      { id: "i1", amount: "4 large", name: "leeks, white and pale green only" },
      { id: "i2", amount: "500g", name: "floury potatoes (Maris Piper, Russet)" },
      { id: "i3", amount: "60g", name: "unsalted butter" },
      { id: "i4", amount: "1.2L", name: "good chicken or vegetable stock" },
      { id: "i5", amount: "150ml", name: "double cream" },
      { id: "i6", amount: "1", name: "bay leaf" },
      { id: "i7", amount: "to taste", name: "salt, white pepper, chives" },
    ],
    steps: [
      { id: "s1", order: 1, description: "Slice the leeks finely and wash thoroughly in cold water — grit hides in the layers." },
      { id: "s2", order: 2, description: "Melt butter in a heavy pot over low heat. Add leeks and a pinch of salt. Sweat for 15 minutes until soft and sweet, never coloured." },
      { id: "s3", order: 3, description: "Peel and dice potatoes into 1cm cubes. Add to the pot with the bay leaf and stock." },
      { id: "s4", order: 4, description: "Simmer gently for 20 minutes until potatoes are completely tender. Remove the bay." },
      { id: "s5", order: 5, description: "Blend until silky-smooth. Stir in the cream, season carefully with salt and white pepper." },
      { id: "s6", order: 6, description: "Serve with a swirl of cream, snipped chives, and a final crack of pepper." },
    ],
    notes: "White pepper, not black — this is a soup that wants to stay pale and elegant. For a thinner soup add more stock; for a richer one, more cream. Leftovers reheat beautifully.",
    createdAt: "2026-01-30T16:05:00.000Z",
  },
];
